### ISSUE TITLE
request

### ISSUE THREAD

**Issue by K4L4Uz** [jkivilin/metamod-p#1]
Where can download the metamod-p linux version 2017-01-15 ?

**Comment by jkivilin** [comment]
What is wrong with 1.21p37?

**Comment by K4L4Uz** [comment]
Everything is OK with version 1.21p37. I noticed that you made some corrections so I wanted to test it.

**Comment by Frisasky** [comment]
well,i compiled that from the lastest git,using gcc 4.9 under debian jessie
https://drive.google.com/open?id=0B2AfzTChLj6aaUZ0eFN5dzItSjg

**Comment by K4L4Uz** [comment]
server will not start ReHLDS
```
Console initialized.
Setting breakpad minidump AppID = 10
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 17:31:42 May 13 2017 (1127)
STEAM Auth Server

   Metamod version 1.21p37 Copyright (c) 2001-2013 Will Day
     Patch: Metamod-P (mm-p) v37 Copyright (c) 2004-2013 Jussi Kivilinna
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
==================
Game DLL version mismatch
DLL version is 140, engine version is 140
The game DLL for cstrike appears to be outdated, check for updates
==================
Host_Error: 

FATAL ERROR (shutting down): Host_Error: 


Segmentation fault
```

**Comment by Frisasky** [comment]
in some games mmp cannot detect the location of game's so file correctly(like sven coop),you need to manually point the server.so location in game launch parameter. trying add following in launch parameter
+localinfo mm_gamedll dlls/server.so
if you using mmp on sven coop,you better install jonny's mmp,which specified written for sven coop

**Comment by jkivilin** [comment]
Please contact ReHLDS for incompatibility issues.

**Comment by K4L4Uz** [comment]
Gamedll is located here /cstrike/dlls/cs.so game is not sven coop.
Please add auto detection.

**Comment by K4L4Uz** [comment]
Gamedll is located here /cstrike/dlls/cs.so game is not sven coop.
Please add auto detection.
