### ISSUE TITLE
Rehlds support ?

### ISSUE THREAD

**Issue by csoyuncu** [jkivilin/metamod-p#8]
i installed p38 but my server crashed. i use latest rehlds engines & dlls

error:
==================
Game DLL version mismatch
DLL version is 140, engine version is 140
The game DLL for cstrike appears to be outdated, check for updates
==================
Host_Error:

FATAL ERROR (shutting down): Host_Error:

**Comment by csoyuncu** [comment]
L 02/12/2018 - 23:22:13: [META] Metamod v1.21p38  2018/02/11
L 02/12/2018 - 23:22:13: [META] by Will Day
L 02/12/2018 - 23:22:13: [META]    http://www.metamod.org/
L 02/12/2018 - 23:22:13: [META]  Patch: Metamod-P (mm-p) v38
L 02/12/2018 - 23:22:13: [META]  by Jussi Kivilinna
L 02/12/2018 - 23:22:13: [META]     http://metamod-p.sourceforge.net/
L 02/12/2018 - 23:22:13: [META] compiled: Feb 11 2018, 11:05:06 EET (optimized)
L 02/12/2018 - 23:22:13: [META] WARNING: GameDLL-Autodetection: Couldn't find gamedll in '/home/sunucular/part1/hlds16/cstrike/dlls'.
L 02/12/2018 - 23:22:13: [META] Recognized game 'cstrike'; using dllfile 'cs.so'
L 02/12/2018 - 23:22:13: [META] WARNING: dll: Couldn't load game DLL /home/sunucular/part1/cs16/46.20.15.190/cstrike/dlls//home/sunucular/part1/hlds16/cstrike/dlls/cs.so: /home/sunucular/part1/cs16/46.20.15.190/cstrike/dlls//home/sunucular/part1/hlds16/cstrike/dlls/cs.so: cannot open shared object file: No such file or directory
L 02/12/2018 - 23:22:13: [META] ERROR: Failure to load game DLL; exiting...
L 02/12/2018 - 23:22:13: [META] WARNING: GetEntityAPI2 called with null pFunctionTable
==================
Game DLL version mismatch
DLL version is 140, engine version is 140
The game DLL for cstrike appears to be outdated, check for updates
==================
Host_Error:

L 02/12/2018 - 23:22:13: FATAL ERROR (shutting down): Host_Error:


FATAL ERROR (shutting down): Host_Error:

**Comment by AleXr64** [comment]
But if manually set gamedll to "dlls/cs.so" in config.ini, metamod starts normally

> game_version
> "game_version" is "5.5.0.291-dev"
> L 02/13/2018 - 23:45:05: World triggered "Round_Start"
> meta version
> Metamod v1.21p38  2018/02/11 (5:13)
> by Will Day
>    http://www.metamod.org/
>  Patch: Metamod-P (mm-p) v38
>  by Jussi Kivilinna
>     http://metamod-p.sourceforge.net/
> compiled: Feb 11 2018, 11:05:06 EET (optimized)
>

**Comment by jkivilin** [comment]
Metamod tries to search gamedll in directory '/home/sunucular/part1/cs16/server1/cstrike/dlls//home/sunucular/part1/hlds16/cstrike/dlls/'. Current path gets duplicated somewhere.

**Comment by Dr-Strange91** [comment]
I think, its solved. So, you should close it.

**Comment by csoyuncu** [comment]
yes it's solved thanks.
